# Malaria data set for the last 12 months of 2024 for malaria cases in Uganda from the ministry of Health

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
from pandas import read_excel 
from IPython.display import display
%matplotlib inline

In [2]:
df = read_excel('/Users/macbook/Documents/GITHUB/malaria/Malaria_prediction/data_malaria.xls')

In [3]:
display(df)

,period name,033B-AP01. OPD New,033B-AP02. Total OPD,033B-AP03. Expected eMTCT Mothers in Appt,033B-AP04. eMTCT Missed Appointments,033B-CD01a. Malaria (diagnosed) - Cases,033B-CD01b. Malaria (diagnosed) - Deaths,033B-CD02a. Dysentery - Cases,033B-CD02b. Dysentery - Deaths,033B-CD02c. Dysentery - Cases Tested,...,033B-CD12a. Plague - Cases,033B-CD12b. Plague- Deaths,033B-CD12c. Plague- Cases Tested,033B-CD12d. Plague- Cases Positive,033B-CD13a. Typhoid Fever - Cases,033B-CD13b. Typhoid Fever- Deaths,033B-CD13c. Typhoid Fever- Cases Tested,033B-CD13d. Typhoid Fever- Cases Positive,033B-CD14a. Hepatitis B - Cases,033B-CD14b. Hepatitis B- Deaths
0,May 2023,2808536.0,3044521.0,41493.0,7618.0,914494.0,306.0,791.0,3.0,NaN,...,NaN,NaN,NaN,NaN,8288.0,53.0,22.0,3.0,791.0,32.0
1,June 2023,3267076.0,3433374.0,46461.0,8072.0,1169201.0,685.0,879.0,4.0,NaN,...,NaN,NaN,NaN,NaN,9091.0,22.0,NaN,NaN,591.0,13.0
2,July 2023,2626526.0,2852837.0,37744.0,7922.0,899466.0,192.0,760.0,11.0,NaN,...,NaN,NaN,NaN,NaN,7687.0,9.0,14.0,4.0,573.0,NaN
3,August 2023,3019946.0,3282068.0,46564.0,11898.0,939092.0,227.0,1321.0,17.0,NaN,...,34.0,16.0,NaN,NaN,9173.0,18.0,34.0,14.0,793.0,6.0
4,September 2023,2147468.0,2336231.0,36550.0,6246.0,873292.0,297.0,921.0,1.0,NaN,...,NaN,8.0,NaN,NaN,7260.0,22.0,25.0,7.0,767.0,1.0
5,October 2023,2309097.0,2509905.0,36469.0,6835.0,713617.0,144.0,1018.0,NaN,NaN,...,26.0,8.0,NaN,NaN,6438.0,61.0,26.0,11.0,548.0,10.0
6,November 2023,3049091.0,3286098.0,49076.0,8380.0,995554.0,514.0,1583.0,NaN,NaN,...,18.0,8.0,NaN,NaN,8324.0,29.0,49.0,22.0,711.0,69.0
7,December 2023,2078021.0,2144334.0,27806.0,5350.0,647512.0,402.0,1013.0,NaN,NaN,...,2.0,NaN,NaN,NaN,5120.0,33.0,36.0,17.0,529.0,10.0
8,January 2024,2461891.0,2726887.0,38542.0,7338.0,729655.0,278.0,1063.0,NaN,NaN,...,11.0,NaN,NaN,NaN,8137.0,5.0,25.0,10.0,774.0,19.0
9,February 2024,3305745.0,3331504.0,48557.0,8833.0,788385.0,522.0,1521.0,5.0,NaN,...,5.0,NaN,NaN,NaN,9578.0,26.0,44.0,4.0,908.0,12.0
10,March 2024,803228968.0,2679901.0,37386.0,7095.0,616163.0,150.0,1481.0,NaN,NaN,...,5.0,NaN,NaN,NaN,6178.0,3.0,31.0,6.0,721.0,24.0
11,April 2024,2458392.0,2459682.0,36386.0,6879.0,479413.0,233.0,1462.0,NaN,NaN,...,2.0,NaN,NaN,NaN,5738.0,7.0,37.0,5.0,708.0,1.0

In [4]:
df.columns

Index(['period name', '033B-AP01. OPD New', '033B-AP02. Total OPD',
       '033B-AP03. Expected eMTCT Mothers in Appt',
       '033B-AP04. eMTCT Missed Appointments',
       '033B-CD01a. Malaria (diagnosed)  - Cases',
       '033B-CD01b. Malaria (diagnosed) - Deaths',
       '033B-CD02a. Dysentery  - Cases', '033B-CD02b. Dysentery - Deaths',
       '033B-CD02c. Dysentery - Cases Tested',
       '033B-CD02d. Dysentery - Cases Positive', '033B-CD03a. SARI - Cases',
       '033B-CD03b. SARI- Deaths', '033B-CD03c. SARI- Cases Tested',
       '033B-CD03d. SARI- Cases Positive',
       '033B-CD04a. Acute Flaccid Paralysis - Cases',
       '033B-CD04b. Acute Flaccid Paralysis- Deaths',
       '033B-CD04c. Acute Flaccid Paral.- Cases Tested',
       '033B-CD04d. Acute Flaccid Paral.- Cases Positive',
       '033B-CD05a. AEFI - Cases', '033B-CD05b. AEFI- Deaths',
       '033B-CD06a. Animal bites(Suspected rabies) - Cases',
       '033B-CD06b. Animal bites(Suspected rabies) - Deaths',
       '033B-CD06c. Animal bites(Suspected rabies) - Cases Tested',
       '033B-CD06d. Animal bites(Suspected rabies) - Cases Positive',
       '033B-CD07a. Bacterial Meningitis  - Cases',
       '033B-CD07b. Bacterial Meningitis - Deaths',
       '033B-CD07c. Bacterial Meningitis - Cases Tested',
       '033B-CD07d. Bacterial Meningitis - Cases Positive',
       '033B-CD08a. Cholera  - Cases', '033B-CD08b. Cholera - Deaths',
       '033B-CD08c. Cholera - Cases Tested',
       '033B-CD08d. Cholera - Cases Positive',
       '033B-CD09a. Guinea Worm - Cases', '033B-CD09b. Guinea Worm- Deaths',
       '033B-CD10a. Measles - Cases', '033B-CD10b. Measles- Deaths',
       '033B-CD10c. Measles- Cases Tested',
       '033B-CD10d. Measles- Cases Positive',
       '033B-CD11a. Neonatal tetanus - Cases',
       '033B-CD11b. Neonatal tetanus- Deaths', '033B-CD12a. Plague - Cases',
       '033B-CD12b. Plague- Deaths', '033B-CD12c. Plague- Cases Tested',
       '033B-CD12d. Plague- Cases Positive',
       '033B-CD13a. Typhoid Fever - Cases',
       '033B-CD13b. Typhoid Fever- Deaths',
       '033B-CD13c. Typhoid Fever- Cases Tested',
       '033B-CD13d. Typhoid Fever- Cases Positive',
       '033B-CD14a. Hepatitis B - Cases', '033B-CD14b. Hepatitis B- Deaths'],
      dtype='object')

In [5]:
# df.drop(index=0,inplace=True)
# display(df)

In [6]:
df.dtypes

period name                                                     object
033B-AP01. OPD New                                             float64
033B-AP02. Total OPD                                           float64
033B-AP03. Expected eMTCT Mothers in Appt                      float64
033B-AP04. eMTCT Missed Appointments                           float64
033B-CD01a. Malaria (diagnosed)  - Cases                       float64
033B-CD01b. Malaria (diagnosed) - Deaths                       float64
033B-CD02a. Dysentery  - Cases                                 float64
033B-CD02b. Dysentery - Deaths                                 float64
033B-CD02c. Dysentery - Cases Tested                           float64
033B-CD02d. Dysentery - Cases Positive                         float64
033B-CD03a. SARI - Cases                                       float64
033B-CD03b. SARI- Deaths                                       float64
033B-CD03c. SARI- Cases Tested                                 float64
033B-CD03d. SARI- Cases Positive                               float64
033B-CD04a. Acute Flaccid Paralysis - Cases                    float64
033B-CD04b. Acute Flaccid Paralysis- Deaths                    float64
033B-CD04c. Acute Flaccid Paral.- Cases Tested                 float64
033B-CD04d. Acute Flaccid Paral.- Cases Positive               float64
033B-CD05a. AEFI - Cases                                       float64
033B-CD05b. AEFI- Deaths                                       float64
033B-CD06a. Animal bites(Suspected rabies) - Cases             float64
033B-CD06b. Animal bites(Suspected rabies) - Deaths            float64
033B-CD06c. Animal bites(Suspected rabies) - Cases Tested      float64
033B-CD06d. Animal bites(Suspected rabies) - Cases Positive    float64
033B-CD07a. Bacterial Meningitis  - Cases                      float64
033B-CD07b. Bacterial Meningitis - Deaths                      float64
033B-CD07c. Bacterial Meningitis - Cases Tested                float64
033B-CD07d. Bacterial Meningitis - Cases Positive              float64
033B-CD08a. Cholera  - Cases                                   float64
033B-CD08b. Cholera - Deaths                                   float64
033B-CD08c. Cholera - Cases Tested                             float64
033B-CD08d. Cholera - Cases Positive                           float64
033B-CD09a. Guinea Worm - Cases                                float64
033B-CD09b. Guinea Worm- Deaths                                float64
033B-CD10a. Measles - Cases                                    float64
033B-CD10b. Measles- Deaths                                    float64
033B-CD10c. Measles- Cases Tested                              float64
033B-CD10d. Measles- Cases Positive                            float64
033B-CD11a. Neonatal tetanus - Cases                           float64
033B-CD11b. Neonatal tetanus- Deaths                           float64
033B-CD12a. Plague - Cases                                     float64
033B-CD12b. Plague- Deaths                                     float64
033B-CD12c. Plague- Cases Tested                               float64
033B-CD12d. Plague- Cases Positive                             float64
033B-CD13a. Typhoid Fever - Cases                              float64
033B-CD13b. Typhoid Fever- Deaths                              float64
033B-CD13c. Typhoid Fever- Cases Tested                        float64
033B-CD13d. Typhoid Fever- Cases Positive                      float64
033B-CD14a. Hepatitis B - Cases                                float64
033B-CD14b. Hepatitis B- Deaths                                float64
dtype: object